export { default as Login } from "./Login"
export { default as Home } from "./Home"
export { default as Create } from "./Create"
export { default as Profile } from "./Profile"
export { default as Details } from "./Details"
export { default as Search } from "./Search"
